esphome:
  name: click-doubleclick-longpress

esp32:
  board: esp32doit-devkit-v1

logger:

globals:
  - id: clicks
    type: int
    restore_value: no
    initial_value: '0'

output:
  - id: red_led
    platform: gpio
    pin: 18
  - id: green_led
    platform: gpio
    pin: 19
  - id: blue_led
    platform: gpio
    pin: 21

binary_sensor:
  - id: pushbutton
    platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 20ms
    on_double_click:
      then:
        - logger.log: double clicked!
        - binary_sensor.template.publish:
            id: pushbutton_longpress
            state: false        
    on_press:
      then:
        - logger.log: on_press
        - globals.set:
            id: clicks
            value: '0'
        - binary_sensor.template.publish:
            id: pushbutton_longpress
            state: true
    on_release:
      then:
        - logger.log: on_release
        - globals.set:
            id: clicks
            value: !lambda |-
              return id(clicks) + 1;

  - id: pushbutton_longpress
    platform: template
    filters:
      - delayed_on: 1.5s
    on_press:
      then:
        - logger.log:
            format: "Number of clicks: %d"
            args: ['id(clicks)']
        - binary_sensor.template.publish:
            id: pushbutton_longpress
            state: false




        





